### ISSUE TITLE
support values less than .1?

### ISSUE THREAD

**Issue by gabevenberg** [DMagic1/Science-Param-Loader#1]
im trying to make the KSC less of a science mine. however, its kinda impossible to do with the multiplier bottoming out at .1

**Comment by DMagic1** [comment]
I think that this can be done by editing the config file found in the [ScienceParamModifier folder](https://github.com/DMagic1/Science-Param-Loader/blob/master/GameData/ScienceParamModifier/ScienceParamModifierConfig.cfg).

Set the values for Kerbin surface to 0.0001, or something like that, you probably shouldn't set it to 0. Those values are only used as defaults for a new game, or for setting the values to default with the modifier window (there should be two buttons, one to set values to stock, one to set values to "default", which means the values from the config file). So you'll have to set the values in the config file, start KSP, then open the window in-game and set the values for Kerbin to default, then don't touch the Surface values slider.

That's probably more trouble than it should be...

**Comment by gabevenberg** [comment]
ah, i was thinking that since the GUI didnt accept it, the plugin wouldn't accept it.
